/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.scorchedcode.JMWLib;

import org.junit.Test;

public class TokenWebViewTest {
    @Test public void testAppHasAGreeting() {
        TokenWebView classUnderTest = new TokenWebView();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
