/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.scorchedcode.JMWLib;

import javafx.application.Application;
import javafx.concurrent.Worker;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.scene.web.WebView;
import javafx.stage.Stage;

import java.net.*;

public class TokenWebView extends Application {

    @Override
    public void start(Stage stage) {
        CookieManager cookies = new CookieManager();
        CookieHandler.setDefault(cookies);
        stage.setTitle("Login to MeWe");
        WebView web = new WebView();
        web.getEngine().load("https://mewe.com/login");
        web.getEngine().getLoadWorker().stateProperty().addListener((observableValue, state, t1) -> {
            if (t1 == Worker.State.SUCCEEDED) {
                if (web.getEngine().getLocation().equalsIgnoreCase("https://mewe.com/myworld")) {
                    try {
                        String csrf = "";
                        String refresh= "";
                        for(HttpCookie httpCookie : cookies.getCookieStore().get(new URI("https://mewe.com"))) {
                            if (httpCookie.getName().equalsIgnoreCase("csrf-token"))
                                csrf = httpCookie.getValue();
                            if (httpCookie.getName().equalsIgnoreCase("refresh-token"))
                                refresh = httpCookie.getValue();
                        }
                        new JMWBuilder().setCSRF(csrf).setRefresh(refresh).build();
                    } catch (URISyntaxException e) {
                        e.printStackTrace();
                    }
                    stage.close();
                }
            }
        });
        web.getEngine().setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36");
        web.setContextMenuEnabled(false);
        VBox vbox = new VBox(web);
        Scene scene = new Scene(vbox, 640, 480);
        stage.setScene(scene);
        stage.show();

    }

    public static void main(String[] args) {
        launch();
    }
}
